### ISSUE TITLE
Trouble with subsequent registrations in iOS 10

### ISSUE THREAD

**Issue by xtiandiaz** [Pushwoosh/pushwoosh-unity#19] opened 2016-10-21 12:15 UTC
I'm experiencing problems with subsequent registrations using the latest plugin. I can't provide conclusive evidence but here's what I've observed:

`Subject: iPhone 8.1 (6S), iOS 10.0.2, 'Limit Ad tracking' enabled and disabled`
1. If the App is launched for the first time, _either with notifications enabled or disabled in the Device settings_, the process will go as expected. Getting debug log from `PWRequestManager` and requests responses for the remote API calls. All good!
2. Unregistering goes as expected too (debug log confirms).
3. Following attempts won't produce any output. But here's the thing, I have the following subsequent lines in the code:

```
Debug.Log("[PushNotificator] Push registration started!");
Pushwoosh.Instance.RegisterForPushNotifications();
```

Upon every attempt I get the above message logged in XCode's console. Nothing comes after it. Toggling a switch to register/unregister while in the App gives no result other than the above message been always logged.
4. I go to device settings and disable push for the App.
5. Come back to the app and try the toggle to register once again and, the registration happens!
6. Unregistering goes well once more.
7. Back to step 3.

**Comment by shaders** [comment] 2016-10-21 21:22
duplicate of https://github.com/Pushwoosh/pushwoosh-unity/issues/18

**Closed as completed by shaders** 2016-10-21 21:22 UTC
