### ISSUE TITLE
AndroidManifest Issue

### ISSUE THREAD

**Issue by MurtazaSadikot** [Pushwoosh/pushwoosh-unity#6] opened 2016-04-05 13:40 UTC
The AndroidManifest.xml that is provided in the unity plugin replaces the original AndroidManifest.xml which is already present in the unity project rather than appending the already existing AndroidManifest.xml.

**Comment by Legendxh** [comment] 2016-05-02 00:58
**I modify the Pushwoosh AndroidManifest.xml and it works with all!**

**Im using Google Play Services 0.9.27**

**Here is WORKING AndroidManifest.xml for Pushwoosh and GooglePlayServices**
**Requeriments (IMPORTANT):**
**_-Imported Pushwoosh package in your project files UNCHANGED_**

**Copy all this code**
http://pastebin.com/1Gir8MJY
1. **Replace** it on your **_<ProjectName>/Assets/Plugins/Android/AndroidManifest.xml_**
2. **Delete** **_android-support-v4.js_** (to avoid "Unable to convert classes to dex format" at compile).
3. In **_AndroidManifest.xml search and replace "YOUR_PACKAGE_NAME"_** with your own package name.

**Use it with sample scene script (PushNotificator.cs) for testing :)**

**Comment by ravaan** [comment] 2016-08-30 21:23
The link has expired can you give the code again ?

**Comment by ivanwidyan** [comment] 2017-01-23 12:17
It doesn't work in my Unity projects. I already delete my android-support-v4 but the console always says about these:

Error: [Temp\StagingArea\AndroidManifest-main.xml:39, D:\Ivan\Seiger AR\Temp\StagingArea\android-libraries\Pushwoosh\AndroidManifest.xml:41] Trying to merge incompatible /manifest/application/service[@name=com.pushwoosh.GCMListenerService] element:
Error: [Temp\StagingArea\AndroidManifest-main.xml:44, D:\Ivan\Seiger AR\Temp\StagingArea\android-libraries\Pushwoosh\AndroidManifest.xml:46] Trying to merge incompatible /manifest/application/service[@name=com.pushwoosh.GCMInstanceIDListenerService] element:

I think the problem is inside the services but I don't know how to fix it

**Comment by viridanti** [comment] 2017-02-07 10:39
Closing dead thread.

**Closed as completed by viridanti** 2017-02-07 10:39 UTC
